heat_template_version: 2016-04-08

#  GfK Online Pricing Intelligence
#  Production Platform Orchestration Template (HEAT)
#  http://docs.openstack.org/developer/heat/template_guide/hot_spec.html
#  http://docs.openstack.org/developer/heat/template_guide/openstack.html

description: |
  This is a template to deploy a windows server

#  VERSION HISTORY
#
#  Version  Date    Author      Comments
#  -------  ----------  ------------  -----------------------------
#  1.0    2016-04-26  Tommy Monk    Initial Version

parameters:

  name_map:
    type: json
    
  index:
    type: string
    
  admin_pass:
    type: string
    
  image:
    type: string
    
  flavor:
    type: string

  network_id:
    type: string
      
  domain:
    type: string
    
  oupath:
    type: string
    
  credential_username:
    type: string

  credential_password:
    type: string

resources:
 block_store_volume:
   type: OS::Cinder::Volume
   properties:
     size: 40
     image: { get_param: image }
     
 server:
    type: OS::Nova::Server
    depends_on: block_store_volume
    properties:
      flavor: { get_param: flavor }
      name: { get_param: [name_map, { get_param: index}] }
      admin_pass: { get_param: admin_pass }
      networks:
      - network: 11111111-1111-1111-1111-111111111111
      - network: { get_param: network_id }
      block_device_mapping:
        - device_name: "c"
          volume_id: { get_resource: block_store_volume }
          delete_on_termination: true
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      personality:
        'c:\cloud-automation\bootstrap.bat':
          str_replace:
            template: powershell.exe -NoProfile -NoLogo -InputFormat None -ExecutionPolicy Bypass -Command "(Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/cogenta/Rackspace-HEAT/master/join_domain.ps1' -OutFile 'join_domain.ps1'); .\join_domain.ps1 -domain '$cDomain' -oupath '$cOUPath' -credential_username '$cCredentialUser' -credential_password '$cCredentialPassword'; del 'C:\cloud-automation\bootstrap.bat';"
            params:
                $cDomain:
                  get_param: domain
                $cOUPath:
                  get_param: oupath
                $cCredentialUser:
                  get_param: credential_username
                $cCredentialPassword:
                  get_param: credential_password
